# Pandas expliqué très simplement (comme à un enfant de 10 ans)

On va utiliser **un seul tableau** : la liste des comptes bancaires de Beobank.

Un compte bancaire, c'est comme une **tirelire** : elle a un numéro, une date où on
l'a ouverte, une monnaie (des euros, des dollars...), et un peu d'argent dedans (ou pas).

On va apprendre, petit pas par petit pas, tout ce qu'on peut faire avec Pandas sur ce
tableau de tirelires. Chaque ligne de code est expliquée simplement.

In [1]:
import pandas as pd   # on sort la boîte à outils Pandas, on lui donne un petit nom : pd
import numpy as np    # une deuxième boîte à outils, pour les calculs : np

## 1. Ouvrir le tableau des tirelires

Le tableau est dans un fichier `CTR.csv` (CTR = "comptes"). On demande à Pandas de
l'ouvrir et de le transformer en un grand tableau, comme un tableau Excel.

In [2]:
# pd.read_csv(fichier) : ouvre le fichier et le transforme en tableau Pandas
# sep=";" : dans ce fichier, les colonnes sont séparées par des points-virgules
# encoding="cp1252" : pour bien lire les lettres avec des accents
tirelires = pd.read_csv("../data/CTR.csv", sep=";", encoding="cp1252")

print("Bravo, le tableau est ouvert !")

Bravo, le tableau est ouvert !

## 2. Regarder à quoi ressemble le tableau

Avant de faire quoi que ce soit, on regarde toujours à quoi ressemble un nouveau
tableau. C'est comme ouvrir un cahier et regarder la première page.

In [4]:
tirelires.head(15)   # .head() : montre les 5 premières lignes du tableau

,IDT_AC,REF_CTR_INN,DAT_OUV_CTR,COD_ECV_CTR,DAT_ECV_CTR,DAT_CLO_CTR,COD_DEV,SLD_CTR,DAT_MAJ_SLD,SLD_DSP,MNT_INI
0,65500004701,29862201102,2024-05-29,6,2025-12-10,2025-12-10,EUR,.,.,.,.
1,65500006391,29912218433,2024-08-07,6,2025-02-05,2025-02-05,EUR,.,.,.,.
2,65500007774,29922113324,2022-01-12,4,2022-01-12,.,EUR,.,.,.,.
3,65500008787,29872222935,2025-01-07,4,2025-01-07,.,EUR,.,2025-10-31,.,.
4,65500014230,29862237513,2025-01-18,6,2025-02-15,2025-02-15,EUR,.,.,.,.
5,65500016903,29892298341,2024-05-29,6,2025-12-10,2025-12-10,EUR,.,2025-10-31,.,.
6,65500017438,29882152002,2020-12-09,4,2020-12-09,.,USD,2.82,2025-02-12,2.82,.
7,65500018665,29242121728,2022-09-28,6,2024-11-27,2024-11-27,EUR,.,.,.,.
8,65500019025,29902113259,2022-02-22,6,2023-01-05,2023-01-05,EUR,.,.,.,.
9,65500021862,29222189161,2021-07-29,6,2024-07-06,2024-07-06,EUR,0.00,2025-10-31,.,0.00
10,65500022341,29102023089,2020-01-23,6,2020-04-24,2020-04-24,AUD,.,2025-10-31,.,.
11,65500025377,29862179085,2021-04-16,6,2022-02-16,2022-02-16,EUR,0.00,2025-12-05,0.00,34425.51
12,65500032486,29262278029,2023-08-25,6,2024-10-04,2024-10-04,EUR,.,2025-10-31,.,.
13,65500033145,29252120420,2022-08-23,4,2022-08-23,.,EUR,361.74,2026-04-01,361.74,.
14,65500033462,29242185041,2021-09-01,4,2021-09-01,.,EUR,0.00,2025-10-31,.,0.00

In [5]:
tirelires.tail(3)   # .tail(3) : montre les 3 dernières lignes

,IDT_AC,REF_CTR_INN,DAT_OUV_CTR,COD_ECV_CTR,DAT_ECV_CTR,DAT_CLO_CTR,COD_DEV,SLD_CTR,DAT_MAJ_SLD,SLD_DSP,MNT_INI
197,65500491523,25304103771,2026-01-09,4,2026-01-09,.,EUR,.,.,.,.
198,65500491571,25244098277,2026-01-09,4,2026-01-09,.,EUR,.,.,.,.
199,65500491575,25754099879,2026-01-09,4,2026-01-09,.,EUR,0.00,.,0.00,.

In [6]:
tirelires.shape   # .shape : dit combien il y a de lignes (de tirelires) et de colonnes (d'informations)

(200, 11)

In [7]:
tirelires.columns   # .columns : donne la liste des noms de colonnes

Index(['IDT_AC', 'REF_CTR_INN', 'DAT_OUV_CTR', 'COD_ECV_CTR', 'DAT_ECV_CTR',
       'DAT_CLO_CTR', 'COD_DEV', 'SLD_CTR', 'DAT_MAJ_SLD', 'SLD_DSP',
       'MNT_INI'],
      dtype='str')

In [8]:
tirelires.sample(3)   # .sample(3) : montre 3 lignes prises au hasard dans le tableau

,IDT_AC,REF_CTR_INN,DAT_OUV_CTR,COD_ECV_CTR,DAT_ECV_CTR,DAT_CLO_CTR,COD_DEV,SLD_CTR,DAT_MAJ_SLD,SLD_DSP,MNT_INI
144,65500400956,29042114176,2022-04-26,6,2024-06-30,2024-06-30,EUR,.,.,.,.
86,65500182676,29482266701,2023-06-08,6,2023-10-05,2023-10-05,EUR,.,.,.,.
129,65500332805,90089387597,2009-09-22,6,2018-07-23,2018-07-23,EUR,0.00,2025-11-28,0.00,6000.00

In [9]:
tirelires.info()   # .info() : un résumé complet -> nombre de lignes, colonnes, et leur type

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   IDT_AC       200 non-null    int64
 1   REF_CTR_INN  200 non-null    int64
 2   DAT_OUV_CTR  200 non-null    str
 3   COD_ECV_CTR  200 non-null    int64
 4   DAT_ECV_CTR  200 non-null    str
 5   DAT_CLO_CTR  200 non-null    str
 6   COD_DEV      200 non-null    str
 7   SLD_CTR      200 non-null    str
 8   DAT_MAJ_SLD  200 non-null    str
 9   SLD_DSP      200 non-null    str
 10  MNT_INI      200 non-null    str
dtypes: int64(3), str(8)
memory usage: 17.3 KB

In [10]:
tirelires.dtypes   # .dtypes : juste le type de chaque colonne (nombre, texte...)

IDT_AC         int64
REF_CTR_INN    int64
DAT_OUV_CTR      str
COD_ECV_CTR    int64
DAT_ECV_CTR      str
DAT_CLO_CTR      str
COD_DEV          str
SLD_CTR          str
DAT_MAJ_SLD      str
SLD_DSP          str
MNT_INI          str
dtype: object

In [15]:
tirelires.describe()   # .describe() : des statistiques (moyenne, minimum, maximum...) sur les colonnes de nombres

             IDT_AC   REF_CTR_INN  COD_ECV_CTR
count  2.000000e+02  2.000000e+02   200.000000
mean   6.550026e+10  4.585308e+10     4.950000
std    1.603949e+05  2.769239e+10     1.001255
min    6.550000e+10  2.507410e+10     4.000000
25%    6.550012e+10  2.914974e+10     4.000000
50%    6.550023e+10  2.968213e+10     4.000000
75%    6.550042e+10  9.008092e+10     6.000000
max    6.550049e+10  9.009739e+10     6.000000

## 3. Donner des noms plus faciles aux colonnes

Les noms des colonnes viennent d'un très vieux logiciel de banque. Ils sont écrits
bizarrement. On va leur donner des noms plus simples à comprendre.

In [16]:
# .rename(columns={ancien_nom: nouveau_nom}) : change le nom d'une ou plusieurs colonnes
tirelires = tirelires.rename(columns={
    "IDT_AC": "numero_tirelire",     # le numéro qui identifie la tirelire
    "DAT_OUV_CTR": "date_ouverture",  # le jour où la tirelire a été ouverte
    "DAT_CLO_CTR": "date_fermeture",  # le jour où la tirelire a été fermée (si elle est fermée)
    "COD_DEV": "monnaie",             # dans quelle monnaie est l'argent (euros, dollars...)
    "SLD_CTR": "argent_dedans",       # combien d'argent il y a dans la tirelire
    "COD_ECV_CTR": "code_statut",     # un code qui dit si la tirelire est ouverte ou fermée
})

tirelires.head(3)

,numero_tirelire,REF_CTR_INN,date_ouverture,code_statut,DAT_ECV_CTR,date_fermeture,monnaie,argent_dedans,DAT_MAJ_SLD,SLD_DSP,MNT_INI
0,65500004701,29862201102,2024-05-29,6,2025-12-10,2025-12-10,EUR,.,.,.,.
1,65500006391,29912218433,2024-08-07,6,2025-02-05,2025-02-05,EUR,.,.,.,.
2,65500007774,29922113324,2022-01-12,4,2022-01-12,.,EUR,.,.,.,.

## 4. Choisir des colonnes

On peut demander à Pandas de ne montrer qu'une seule colonne, ou juste quelques-unes.

In [17]:
tirelires["argent_dedans"]   # une seule colonne entre crochets -> Pandas la montre comme une liste

0         .
1         .
2         .
3         .
4         .
       ...
195       .
196       .
197       .
198       .
199    0.00
Name: argent_dedans, Length: 200, dtype: str

In [18]:
tirelires[["numero_tirelire", "monnaie", "argent_dedans"]]   # une LISTE de colonnes entre deux crochets

     numero_tirelire monnaie argent_dedans
0        65500004701     EUR             .
1        65500006391     EUR             .
2        65500007774     EUR             .
3        65500008787     EUR             .
4        65500014230     EUR             .
..               ...     ...           ...
195      65500491455     EUR             .
196      65500491460     EUR             .
197      65500491523     EUR             .
198      65500491571     EUR             .
199      65500491575     EUR          0.00

[200 rows x 3 columns]

In [19]:
tirelires.select_dtypes(include="number")   # select_dtypes : garde seulement les colonnes qui contiennent des nombres

     numero_tirelire  REF_CTR_INN  code_statut
0        65500004701  29862201102            6
1        65500006391  29912218433            6
2        65500007774  29922113324            4
3        65500008787  29872222935            4
4        65500014230  29862237513            6
..               ...          ...          ...
195      65500491455  25184084526            4
196      65500491460  25804103498            4
197      65500491523  25304103771            4
198      65500491571  25244098277            4
199      65500491575  25754099879            4

[200 rows x 3 columns]

## 5. Choisir des lignes

`.loc` et `.iloc` servent à choisir une ou plusieurs lignes précises dans le tableau.

In [25]:
tirelires.iloc[0]  # .iloc[0] : la toute première ligne du tableau (position 0)

REF_CTR_INN       25754099879
date_fermeture              .
Name: 199, dtype: object

In [26]:
tirelires.iloc[0:3]   # .iloc[0:3] : les 3 premières lignes (positions 0, 1, 2)

,numero_tirelire,REF_CTR_INN,date_ouverture,code_statut,DAT_ECV_CTR,date_fermeture,monnaie,argent_dedans,DAT_MAJ_SLD,SLD_DSP,MNT_INI
0,65500004701,29862201102,2024-05-29,6,2025-12-10,2025-12-10,EUR,.,.,.,.
1,65500006391,29912218433,2024-08-07,6,2025-02-05,2025-02-05,EUR,.,.,.,.
2,65500007774,29922113324,2022-01-12,4,2022-01-12,.,EUR,.,.,.,.

In [27]:
tirelires.loc[0, "argent_dedans"]   # .loc[ligne, colonne] : va chercher UNE case précise dans le tableau

'.'

## 6. Les cases vides

Dans ce fichier, une case vide (on ne sait pas combien il y a d'argent) est écrite
avec un simple point `"."`. Il faut d'abord dire à Pandas que ça veut dire "je ne
sais pas", avec une vraie valeur manquante.

In [28]:
# .replace(".", pd.NA) : remplace le texte "." par une vraie valeur manquante Pandas
tirelires = tirelires.replace(".", pd.NA)

tirelires["argent_dedans"].isna().sum()   # .isna() : Vrai si la case est vide. .sum() : compte les cases vides

np.int64(137)

In [29]:
tirelires["argent_dedans"].notna().sum()   # .notna() : Vrai si la case N'EST PAS vide

np.int64(63)

In [30]:
# .dropna(subset=[...]) : enlève les lignes où cette colonne est vide
tirelires_avec_argent_connu = tirelires.dropna(subset=["argent_dedans"])
print(tirelires_avec_argent_connu.shape[0], "tirelires où on connaît le montant")

63 tirelires où on connaît le montant

In [31]:
# .fillna(valeur) : remplace les cases vides par une valeur de secours
exemple = tirelires["argent_dedans"].fillna("Inconnu")
exemple.head()

0    Inconnu
1    Inconnu
2    Inconnu
3    Inconnu
4    Inconnu
Name: argent_dedans, dtype: str

In [32]:
lignes_inconnues = tirelires[
    tirelires.isna().any(axis=1) |
    tirelires.eq("Inconnu").any(axis=1)
]

lignes_inconnues

,numero_tirelire,REF_CTR_INN,date_ouverture,code_statut,DAT_ECV_CTR,date_fermeture,monnaie,argent_dedans,DAT_MAJ_SLD,SLD_DSP,MNT_INI
0,65500004701,29862201102,2024-05-29,6,2025-12-10,2025-12-10,EUR,NaN,NaN,NaN,NaN
1,65500006391,29912218433,2024-08-07,6,2025-02-05,2025-02-05,EUR,NaN,NaN,NaN,NaN
2,65500007774,29922113324,2022-01-12,4,2022-01-12,NaN,EUR,NaN,NaN,NaN,NaN
3,65500008787,29872222935,2025-01-07,4,2025-01-07,NaN,EUR,NaN,2025-10-31,NaN,NaN
4,65500014230,29862237513,2025-01-18,6,2025-02-15,2025-02-15,EUR,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
195,65500491455,25184084526,2026-01-07,4,2026-01-07,NaN,EUR,NaN,NaN,NaN,NaN
196,65500491460,25804103498,2026-01-07,4,2026-01-07,NaN,EUR,NaN,NaN,NaN,NaN
197,65500491523,25304103771,2026-01-09,4,2026-01-09,NaN,EUR,NaN,NaN,NaN,NaN
198,65500491571,25244098277,2026-01-09,4,2026-01-09,NaN,EUR,NaN,NaN,NaN,NaN
199,65500491575,25754099879,2026-01-09,4,2026-01-09,NaN,EUR,0.00,NaN,0.00,NaN

## 7. Dire à Pandas que c'est un nombre ou une date

Au départ, TOUT est écrit comme du texte dans le fichier, même les nombres et les
dates. Il faut le dire explicitement à Pandas. **On fait ça maintenant, AVANT de
filtrer sur des nombres**, sinon Pandas ne peut pas comparer du texte à un nombre.

In [33]:
# pd.to_numeric(colonne, errors="coerce") : transforme le texte en vrai nombre
# errors="coerce" : si ce n'est pas un nombre, on met une case vide au lieu de planter
tirelires["argent_dedans"] = pd.to_numeric(tirelires["argent_dedans"], errors="coerce")

tirelires["argent_dedans"].dtype   # maintenant c'est bien un nombre (float64)

dtype('float64')

In [34]:
# pd.to_datetime(colonne, format=...) : transforme le texte en vraie date
# format="%Y-%m-%d" : les dates sont écrites "année-mois-jour"
tirelires["date_ouverture"] = pd.to_datetime(tirelires["date_ouverture"], format="%Y-%m-%d", errors="coerce")
tirelires["date_fermeture"] = pd.to_datetime(tirelires["date_fermeture"], format="%Y-%m-%d", errors="coerce")

tirelires["date_ouverture"].head()

0   2024-05-29
1   2024-08-07
2   2022-01-12
3   2025-01-07
4   2025-01-18
Name: date_ouverture, dtype: datetime64[us]

In [49]:
# .map({...}) : remplace chaque code par un mot qu'on comprend (4 = ouverte, 6 = fermée)
tirelires["statut"] = tirelires["code_statut"].map({4: "Ouverte", 6: "Fermée"})
tirelires["statut"].value_counts()

statut
Ouverte    105
Fermée      95
Name: count, dtype: int64

In [52]:
# 1. Transformer toutes les colonnes de dates
colonnes_dates = [
    "date_ouverture",
    "date_fermeture",
    "DAT_ECV_CTR",
    "DAT_MAJ_SLD",
]

for colonne in colonnes_dates:
    if colonne in tirelires.columns:
        tirelires[colonne] = pd.to_datetime(
            tirelires[colonne],
            errors="coerce"
        )

# 2. Extraire des informations de la date d'ouverture
tirelires["annee_ouverture"] = tirelires["date_ouverture"].dt.year
tirelires["mois_ouverture"] = tirelires["date_ouverture"].dt.month
tirelires["nom_mois_ouverture"] = tirelires["date_ouverture"].dt.month_name()
tirelires["trimestre_ouverture"] = tirelires["date_ouverture"].dt.quarter
tirelires["jour_semaine_ouverture"] = tirelires["date_ouverture"].dt.day_name()
tirelires["jour_du_mois"] = tirelires["date_ouverture"].dt.day

# 3. Savoir si la tirelire est fermée
tirelires["est_fermee"] = tirelires["date_fermeture"].notna()

# 4. Durée entre l'ouverture et la fermeture
tirelires["duree_jours"] = (
    tirelires["date_fermeture"] - tirelires["date_ouverture"]
).dt.days

tirelires["duree_annees"] = tirelires["duree_jours"] / 365.25

# 5. Durée jusqu'à aujourd'hui pour les tirelires encore ouvertes
aujourdhui = pd.Timestamp.today().normalize()

tirelires["jours_depuis_ouverture"] = (
    aujourdhui - tirelires["date_ouverture"]
).dt.days

# 6. Début et fin du mois d'ouverture
tirelires["debut_mois_ouverture"] = (
    tirelires["date_ouverture"].dt.to_period("M").dt.start_time
)

tirelires["fin_mois_ouverture"] = (
    tirelires["date_ouverture"].dt.to_period("M").dt.end_time
)

# 7. Filtrer entre deux dates
date_debut = pd.Timestamp("2024-01-01")
date_fin = pd.Timestamp("2025-12-31")

tirelires_ouvertes_periode = tirelires[
    tirelires["date_ouverture"].between(date_debut, date_fin)
]

# 8. Filtrer les tirelires ouvertes aujourd'hui
tirelires_ouvertes = tirelires[
    tirelires["date_fermeture"].isna()
]

# 9. Trier par date
tirelires_triees_par_date = tirelires.sort_values(
    "date_ouverture"
)

# 10. Compter les ouvertures par année
ouvertures_par_annee = (
    tirelires.groupby("annee_ouverture")
    .size()
    .sort_index()
)

# 11. Compter les ouvertures par mois
ouvertures_par_mois = (
    tirelires["date_ouverture"]
    .dt.to_period("M")
    .value_counts()
    .sort_index()
)

# 12. Trouver la plus ancienne et la plus récente tirelire
date_plus_ancienne = tirelires["date_ouverture"].min()
date_plus_recente = tirelires["date_ouverture"].max()

print("Première ouverture :", date_plus_ancienne)
print("Dernière ouverture :", date_plus_recente)

# Afficher un résumé
tirelires[
    [
        "numero_tirelire",
        "date_ouverture",
        "date_fermeture",
        "annee_ouverture",
        "nom_mois_ouverture",
        "duree_jours",
        "est_fermee",
    ]
].head()

Première ouverture : 2009-08-28 00:00:00
Dernière ouverture : 2026-06-27 00:00:00

,numero_tirelire,date_ouverture,date_fermeture,annee_ouverture,nom_mois_ouverture,duree_jours,est_fermee
0,65500004701,2024-05-29,2025-12-10,2024,May,560.0,True
1,65500006391,2024-08-07,2025-02-05,2024,August,182.0,True
2,65500007774,2022-01-12,NaT,2022,January,NaN,False
3,65500008787,2025-01-07,NaT,2025,January,NaN,False
4,65500014230,2025-01-18,2025-02-15,2025,January,28.0,True

## 8. Ne garder que certaines tirelires (filtrer)

Maintenant que `argent_dedans` est un vrai nombre, on peut demander à Pandas de ne
garder QUE les lignes qui respectent une condition. C'est comme trier des cartes :
on garde seulement celles qui nous intéressent.

In [50]:
tirelires["monnaie"] == "EUR"   # une condition -> Pandas répond Vrai (True) ou Faux (False) pour chaque ligne

0      True
1      True
2      True
3      True
4      True
       ...
195    True
196    True
197    True
198    True
199    True
Name: monnaie, Length: 200, dtype: bool

In [39]:
tirelires_en_euros = tirelires[tirelires["monnaie"] == "EUR"]   # on garde SEULEMENT les lignes où c'est Vrai
print(tirelires_en_euros.shape[0], "tirelires en euros")

193 tirelires en euros

In [51]:
# ^ veut dire "OU exclusif" (XOR) :
# une seule des deux conditions doit être vraie, mais pas les deux

condition_euros = tirelires["monnaie"] == "EUR"
condition_riche = tirelires["argent_dedans"] > 1000
tirelires_xor = tirelires[condition_euros ^ condition_riche]
tirelires_xor[["numero_tirelire", "monnaie", "argent_dedans"]].head()

   numero_tirelire monnaie  argent_dedans
0      65500004701     EUR            NaN
1      65500006391     EUR            NaN
2      65500007774     EUR            NaN
3      65500008787     EUR            NaN
4      65500014230     EUR            NaN

In [40]:
# & veut dire "ET" : les DEUX conditions doivent être vraies
tirelires_riches_en_euros = tirelires[(tirelires["monnaie"] == "EUR") & (tirelires["argent_dedans"] > 1000)]
tirelires_riches_en_euros.head()

,numero_tirelire,REF_CTR_INN,date_ouverture,code_statut,DAT_ECV_CTR,date_fermeture,monnaie,argent_dedans,DAT_MAJ_SLD,SLD_DSP,MNT_INI,statut
18,65500050418,29282017114,2020-12-01,6,2024-08-01,2024-08-01,EUR,1219.68,2025-10-31,NaN,0.00,Fermée
48,65500115203,90087852236,2009-09-02,4,2009-09-02,NaT,EUR,3718.53,2026-05-18,3718.53,NaN,Ouverte
66,65500153407,29762342182,2025-04-03,4,2025-04-03,NaT,EUR,3279.78,2026-05-15,3279.78,NaN,Ouverte
72,65500163296,29762182482,2021-07-23,4,2021-07-23,NaT,EUR,26168.60,2026-05-27,26168.60,NaN,Ouverte
96,65500204394,90080911729,2011-11-17,4,2018-11-25,NaT,EUR,79156.24,2026-05-27,NaN,NaN,Ouverte

In [41]:
# .isin([...]) : la valeur est-elle dans cette liste ?
tirelires_etrangeres = tirelires[tirelires["monnaie"].isin(["USD", "AUD", "NOK"])]
tirelires_etrangeres[["numero_tirelire", "monnaie"]]

     numero_tirelire monnaie
6        65500017438     USD
10       65500022341     AUD
103      65500248622     NOK
117      65500292479     USD
153      65500451620     USD
154      65500451621     USD
166      65500477169     USD

## 9. Trier le tableau

On peut ranger les tirelires de la plus pauvre à la plus riche, ou l'inverse.

In [42]:
tirelires.sort_values("argent_dedans").head(3)   # tri du plus petit montant au plus grand

,numero_tirelire,REF_CTR_INN,date_ouverture,code_statut,DAT_ECV_CTR,date_fermeture,monnaie,argent_dedans,DAT_MAJ_SLD,SLD_DSP,MNT_INI,statut
138,65500380735,90095198742,2018-07-16,4,2018-07-16,NaT,EUR,-201694.93,2026-03-31,0.00,282000.00,Ouverte
59,65500136358,29612114154,2022-02-11,4,2022-05-25,NaT,EUR,-174000.00,2025-12-02,0.00,174000.00,Ouverte
115,65500282945,29682136513,2022-09-05,4,2022-12-09,NaT,EUR,-162400.00,2025-12-02,0.00,162400.00,Ouverte

In [43]:
tirelires.sort_values("argent_dedans", ascending=False).head(3)   # ascending=False : tri du plus grand au plus petit

,numero_tirelire,REF_CTR_INN,date_ouverture,code_statut,DAT_ECV_CTR,date_fermeture,monnaie,argent_dedans,DAT_MAJ_SLD,SLD_DSP,MNT_INI,statut
96,65500204394,90080911729,2011-11-17,4,2018-11-25,NaT,EUR,79156.24,2026-05-27,NaN,NaN,Ouverte
72,65500163296,29762182482,2021-07-23,4,2021-07-23,NaT,EUR,26168.60,2026-05-27,26168.60,NaN,Ouverte
155,65500451888,90093430936,2018-03-12,4,2018-03-12,NaT,EUR,15348.70,2026-05-26,15348.70,NaN,Ouverte

In [55]:
tirelires.nlargest(5, "argent_dedans")[["numero_tirelire", "argent_dedans"]]   # les 5 tirelires les plus riches

     numero_tirelire  argent_dedans
96       65500204394       79156.24
72       65500163296       26168.60
155      65500451888       15348.70
48       65500115203        3718.53
66       65500153407        3279.78

In [45]:
tirelires.nsmallest(5, "argent_dedans")[["numero_tirelire", "argent_dedans"]]   # les 5 tirelires les plus pauvres (ou en dette)

     numero_tirelire  argent_dedans
138      65500380735     -201694.93
59       65500136358     -174000.00
115      65500282945     -162400.00
84       65500182205     -129247.05
55       65500123918      -65288.47

## 10. Créer de nouvelles colonnes

On peut fabriquer de nouvelles informations à partir de celles qu'on a déjà.

In [46]:
# np.where(condition, si_vrai, si_faux) : un "SI... SINON..." qui marche sur tout le tableau d'un coup
tirelires["en_dette"] = np.where(tirelires["argent_dedans"] < 0, "Oui", "Non")
tirelires["en_dette"].value_counts()

en_dette
Non    187
Oui     13
Name: count, dtype: int64

In [ ]:
SI condition ALORS valeur_si_vrai SINON valeur_si_faux

In [47]:
# pd.cut(colonne, bins=..., labels=...) : range les nombres dans des "boîtes" (des tranches)
bornes = [-1_000_000, 0, 1000, 10000, 1_000_000]
noms_des_boites = ["En dette", "Petite tirelire", "Tirelire moyenne", "Grosse tirelire"]
tirelires["taille_tirelire"] = pd.cut(tirelires["argent_dedans"], bins=bornes, labels=noms_des_boites)
tirelires["taille_tirelire"].value_counts()

taille_tirelire
En dette            51
Petite tirelire      6
Tirelire moyenne     3
Grosse tirelire      3
Name: count, dtype: int64

In [ ]:
# .apply(une_fonction) : applique notre propre fonction à chaque valeur d'une colonne
def dire_bravo_ou_dommage(argent):
    if pd.isna(argent):
        return "On ne sait pas"
    elif argent >= 0:
        return "Bravo !"
    else:
        return "Dommage..."

tirelires["message"] = tirelires["argent_dedans"].apply(dire_bravo_ou_dommage)
tirelires["message"].value_counts()

In [ ]:
# Définir une fonction qui transforme un montant en message
def dire_bravo_ou_dommage(argent):
    # Vérifier si le montant est manquant
    if pd.isna(argent):
        # Message affiché lorsque le montant est inconnu
        return "On ne sait pas"

    # Vérifier si le montant est positif ou égal à zéro
    elif argent >= 0:
        # Message affiché pour un montant positif ou nul
        return "Bravo !"

    # Si le montant est négatif
    else:
        # Message affiché lorsqu'il y a une dette
        return "Dommage..."


# Appliquer la fonction à chaque valeur de la colonne "argent_dedans"
# Le résultat est enregistré dans une nouvelle colonne appelée "message"
tirelires["message"] = tirelires["argent_dedans"].apply(
    dire_bravo_ou_dommage
)

# Compter le nombre de tirelires pour chaque message
tirelires["message"].value_counts()

## 11. Jouer avec le texte

Il existe plein de petits outils pour manipuler du texte dans une colonne, avec `.str`.

In [56]:
tirelires["monnaie"].str.lower()   # .str.lower() : met tout en minuscules

0      eur
1      eur
2      eur
3      eur
4      eur
      ...
195    eur
196    eur
197    eur
198    eur
199    eur
Name: monnaie, Length: 200, dtype: str

In [64]:
tirelires["monnaie"].str.upper().head(3)   # .str.upper() : met tout en majuscules

0    EUR
1    EUR
2    EUR
Name: monnaie, dtype: str

In [60]:
tirelires["monnaie"].str.len()   # .str.len() : compte le nombre de lettres de chaque valeur

0      3
1      3
2      3
3      3
4      3
      ..
195    3
196    3
197    3
198    3
199    3
Name: monnaie, Length: 200, dtype: int64

In [61]:
# .str.contains("...") : Vrai si le texte contient ce qu'on cherche
tirelires[tirelires["monnaie"].str.contains("D")][["numero_tirelire", "monnaie"]].head()

     numero_tirelire monnaie
6        65500017438     USD
10       65500022341     AUD
117      65500292479     USD
153      65500451620     USD
154      65500451621     USD

## 12. Jouer avec les dates

Une fois qu'une colonne est une vraie date, on peut en sortir plein d'informations
avec `.dt`.

In [65]:
# Extraire encore plus d'informations à partir des colonnes de dates déjà transformées

# Semaine de l'année et jour de l'année
tirelires["semaine_ouverture"] = tirelires["date_ouverture"].dt.isocalendar().week
tirelires["jour_annee_ouverture"] = tirelires["date_ouverture"].dt.dayofyear

# Est-ce un jour de week-end ?
tirelires["est_weekend_ouverture"] = tirelires["date_ouverture"].dt.dayofweek >= 5

# Est-ce le début ou la fin du mois ?
tirelires["est_debut_mois"] = tirelires["date_ouverture"].dt.is_month_start
tirelires["est_fin_mois"] = tirelires["date_ouverture"].dt.is_month_end

# Est-ce le début ou la fin de l'année ?
tirelires["est_debut_annee"] = tirelires["date_ouverture"].dt.is_year_start
tirelires["est_fin_annee"] = tirelires["date_ouverture"].dt.is_year_end

# Année bissextile ?
tirelires["annee_bissextile"] = tirelires["date_ouverture"].dt.is_leap_year

# Nombre de jours dans le mois d'ouverture
tirelires["jours_dans_le_mois"] = tirelires["date_ouverture"].dt.days_in_month

# Comparer la date d'ouverture à une date précise avec des décalages (DateOffset)
tirelires["date_ouverture_plus_1an"] = tirelires["date_ouverture"] + pd.DateOffset(years=1)
tirelires["date_ouverture_moins_1mois"] = tirelires["date_ouverture"] - pd.DateOffset(months=1)

# Différence en mois complets entre ouverture et fermeture (ou aujourd'hui si toujours ouverte)
date_reference = tirelires["date_fermeture"].fillna(aujourdhui)
tirelires["duree_mois"] = (
    (date_reference.dt.year - tirelires["date_ouverture"].dt.year) * 12
    + (date_reference.dt.month - tirelires["date_ouverture"].dt.month)
)

# Regrouper par trimestre d'ouverture
ouvertures_par_trimestre = (
    tirelires["date_ouverture"]
    .dt.to_period("Q")
    .value_counts()
    .sort_index()
)

# Regrouper par semaine ISO
ouvertures_par_semaine = (
    tirelires.groupby("semaine_ouverture")
    .size()
    .sort_index()
)

# Utiliser un DatetimeIndex pour rééchantillonner (resample) le nombre d'ouvertures par mois
tirelires_par_date = tirelires.set_index("date_ouverture").sort_index()
ouvertures_resample_mensuel = tirelires_par_date.resample("ME").size()

# Décalage de dates (shift) : comparer chaque ouverture à la précédente (dans l'ordre chronologique)
tirelires_triees_par_date_2 = tirelires.sort_values("date_ouverture").copy()
tirelires_triees_par_date_2["date_ouverture_precedente"] = tirelires_triees_par_date_2["date_ouverture"].shift(1)
tirelires_triees_par_date_2["jours_depuis_ouverture_precedente"] = (
    tirelires_triees_par_date_2["date_ouverture"] - tirelires_triees_par_date_2["date_ouverture_precedente"]
).dt.days

# Aperçu de toutes ces nouvelles colonnes liées aux dates
tirelires[
    [
        "numero_tirelire",
        "date_ouverture",
        "semaine_ouverture",
        "jour_annee_ouverture",
        "est_weekend_ouverture",
        "est_debut_mois",
        "est_fin_mois",
        "annee_bissextile",
        "jours_dans_le_mois",
        "duree_mois",
    ]
].head(10)

,numero_tirelire,date_ouverture,semaine_ouverture,jour_annee_ouverture,est_weekend_ouverture,est_debut_mois,est_fin_mois,annee_bissextile,jours_dans_le_mois,duree_mois
0,65500004701,2024-05-29,22,150,False,False,False,True,31,19
1,65500006391,2024-08-07,32,220,False,False,False,True,31,6
2,65500007774,2022-01-12,2,12,False,False,False,False,31,56
3,65500008787,2025-01-07,2,7,False,False,False,False,31,20
4,65500014230,2025-01-18,3,18,True,False,False,False,31,1
5,65500016903,2024-05-29,22,150,False,False,False,True,31,19
6,65500017438,2020-12-09,50,344,False,False,False,True,31,69
7,65500018665,2022-09-28,39,271,False,False,False,False,30,26
8,65500019025,2022-02-22,8,53,False,False,False,False,28,11
9,65500021862,2021-07-29,30,210,False,False,False,False,31,36

In [62]:
tirelires["annee_ouverture"] = tirelires["date_ouverture"].dt.year    # .dt.year : l'année de la date
tirelires["mois_ouverture"] = tirelires["date_ouverture"].dt.month    # .dt.month : le mois (1 à 12)
tirelires[["date_ouverture", "annee_ouverture", "mois_ouverture"]].head()

  date_ouverture  annee_ouverture  mois_ouverture
0     2024-05-29             2024               5
1     2024-08-07             2024               8
2     2022-01-12             2022               1
3     2025-01-07             2025               1
4     2025-01-18             2025               1

In [59]:
# on calcule combien de jours se sont écoulés depuis l'ouverture de chaque tirelire
aujourdhui = pd.Timestamp.today()   # la date d'aujourd'hui
tirelires["jours_depuis_ouverture"] = (aujourdhui - tirelires["date_ouverture"]).dt.days
tirelires[["date_ouverture", "jours_depuis_ouverture"]].head()

  date_ouverture  jours_depuis_ouverture
0     2024-05-29                     842
1     2024-08-07                     772
2     2022-01-12                    1710
3     2025-01-07                     619
4     2025-01-18                     608

In [ ]:
# Filtrer par ANNÉE : garder seulement les tirelires ouvertes en 2025
tirelires_2025 = tirelires[tirelires["date_ouverture"].dt.year == 2025]
print(len(tirelires_2025), "tirelires ouvertes en 2025")

# Filtrer par MOIS : garder seulement les tirelires ouvertes en janvier (mois 1)
tirelires_janvier = tirelires[tirelires["date_ouverture"].dt.month == 1]
print(len(tirelires_janvier), "tirelires ouvertes en janvier")

# Filtrer par JOUR : garder seulement les tirelires ouvertes un lundi (0 = lundi, 6 = dimanche)
tirelires_lundi = tirelires[tirelires["date_ouverture"].dt.dayofweek == 0]
print(len(tirelires_lundi), "tirelires ouvertes un lundi")

# On peut combiner avec & : année 2025 ET mois de janvier
tirelires_janvier_2025 = tirelires[
    (tirelires["date_ouverture"].dt.year == 2025) &
    (tirelires["date_ouverture"].dt.month == 1)
]

# .between() : garder les tirelires ouvertes ENTRE deux dates
tirelires_entre_deux_dates = tirelires[
    tirelires["date_ouverture"].between("2025-01-01", "2025-12-31")
]

# .isin([...]) : garder les tirelires ouvertes dans l'une de ces années
tirelires_annees_recentes = tirelires[
    tirelires["date_ouverture"].dt.year.isin([2024, 2025, 2026])
]

# .dt.to_period("M") : comparer directement un mois entier (ex : "2025-01")
tirelires_mois_precis = tirelires[
    tirelires["date_ouverture"].dt.to_period("M") == "2025-01"
]

tirelires_janvier_2025[["numero_tirelire", "date_ouverture"]].head()

In [67]:
colonnes_dates = [
    "date_ouverture",
    "date_fermeture",
    "DAT_ECV_CTR",
    "DAT_MAJ_SLD",
]

## 13. Les doublons (deux fois la même ligne)

Parfois, une même ligne se retrouve par erreur deux fois dans un tableau. Il faut
savoir les repérer.

In [ ]:
tirelires.duplicated().sum()   # .duplicated() : Vrai si la ligne est identique à une ligne déjà vue avant. .sum() : les compte

In [ ]:
tirelires_sans_doublons = tirelires.drop_duplicates()   # .drop_duplicates() : enlève les lignes en double
print(tirelires.shape[0], "->", tirelires_sans_doublons.shape[0])

## 14. Compter des choses

Combien de tirelires en euros ? Combien de monnaies différentes ? Pandas compte
très vite pour nous.

In [ ]:
tirelires["monnaie"].unique()   # .unique() : la liste des monnaies différentes, sans les compter

In [ ]:
tirelires["monnaie"].nunique()   # .nunique() : le NOMBRE de monnaies différentes

In [ ]:
tirelires["monnaie"].value_counts()   # .value_counts() : compte combien de tirelires il y a pour chaque monnaie

In [ ]:
(tirelires["monnaie"].value_counts(normalize=True) * 100).round(1)   # normalize=True : donne un pourcentage plutôt qu'un compte

## 15. Regrouper les tirelires par paquet

`.groupby()` fait des paquets de lignes qui se ressemblent (par exemple, toutes les
tirelires de la même monnaie), puis on calcule quelque chose sur chaque paquet.

In [ ]:
tirelires.groupby("monnaie").size()   # un paquet par monnaie, .size() compte les tirelires de chaque paquet

In [ ]:
# .agg({...}) : plusieurs calculs différents en une fois, pour chaque paquet
tirelires.groupby("statut").agg(
    nombre=("numero_tirelire", "count"),
    argent_moyen=("argent_dedans", "mean"),
    argent_total=("argent_dedans", "sum"),
)

In [ ]:
# .transform() : donne, pour CHAQUE ligne, la moyenne de son propre paquet (sans réduire le tableau)
tirelires["argent_moyen_de_sa_monnaie"] = tirelires.groupby("monnaie")["argent_dedans"].transform("mean")
tirelires[["numero_tirelire", "monnaie", "argent_dedans", "argent_moyen_de_sa_monnaie"]].head()

## 16. Un tableau qui croise deux informations

`pd.crosstab()` et `.pivot_table()` fabriquent un tableau à double entrée, comme un
tableau de conversion : une info en ligne, une info en colonne.

In [ ]:
pd.crosstab(tirelires["monnaie"], tirelires["statut"])   # combien de tirelires pour chaque monnaie x chaque statut

In [ ]:
tirelires.pivot_table(values="argent_dedans", index="statut", columns="monnaie", aggfunc="mean")

## 17. Assembler deux tableaux (bonus)

Il existe un DEUXIÈME petit tableau chez Beobank, qui dit à quel client appartient
chaque tirelire (`TIE_X_CTR.csv`). On peut ASSEMBLER les deux tableaux avec `.merge()`,
comme deux moitiés d'un puzzle qui s'emboîtent grâce à un numéro commun.

In [ ]:
proprietaires = pd.read_csv("../data/TIE_X_CTR.csv", sep=";", encoding="cp1252")
proprietaires = proprietaires.rename(columns={"IDT_AC": "numero_tirelire", "NUM_TIE": "numero_client"})

# .merge(autre_tableau, on="colonne_commune") : assemble les deux tableaux grâce à "numero_tirelire"
tirelires_avec_proprietaire = tirelires.merge(
    proprietaires[["numero_tirelire", "numero_client"]], on="numero_tirelire", how="left"
)
tirelires_avec_proprietaire[["numero_tirelire", "numero_client", "argent_dedans"]].head()

In [ ]:
# pd.concat([...]) : empile deux tableaux l'un sur l'autre (pas côte à côte, comme merge, mais l'un SOUS l'autre)
trois_premieres = tirelires.head(3)
trois_dernieres = tirelires.tail(3)
pd.concat([trois_premieres, trois_dernieres])[["numero_tirelire", "argent_dedans"]]

## 18. Changer quelle colonne sert de "numéro de ligne"

D'habitude, Pandas numérote les lignes tout seul (0, 1, 2...). On peut lui dire
d'utiliser une de nos colonnes à la place, pour aller chercher une tirelire plus vite.

In [ ]:
# .set_index("colonne") : utilise cette colonne comme numéro de ligne
tirelires_indexees = tirelires.set_index("numero_tirelire")
tirelires_indexees.loc[65500004701]   # on va directement chercher LA tirelire numéro 65500004701

In [ ]:
tirelires_indexees.reset_index().head(2)   # .reset_index() : remet une numérotation normale 0, 1, 2...

## 19. Additionner petit à petit (les cumuls)

`.cumsum()` fait une addition qui grossit ligne après ligne : le total "jusqu'ici".

In [ ]:
tirelires_triees = tirelires.sort_values("date_ouverture")
tirelires_triees["numero_dans_lordre"] = range(1, len(tirelires_triees) + 1)
tirelires_triees["numero_dans_lordre"].tail()   # à la dernière ligne, on doit retrouver le nombre total de tirelires

## 20. Garder une trace (enregistrer le tableau)

On peut sauvegarder notre tableau de résultats dans un fichier, pour le rouvrir plus
tard, ou l'envoyer à quelqu'un.

In [ ]:
resultat = tirelires.groupby("monnaie")["argent_dedans"].mean()
resultat.to_csv("argent_moyen_par_monnaie.csv")   # .to_csv() : écrit le résultat dans un fichier
print("Fichier enregistré !")

## 21. Faire une copie avant de modifier

Quand on prend un petit bout du tableau pour le modifier, il vaut mieux en faire une
VRAIE copie avec `.copy()`, sinon Pandas peut se plaindre.

In [ ]:
tirelires_usd = tirelires[tirelires["monnaie"] == "USD"].copy()   # .copy() : une copie indépendante, sûre à modifier
tirelires_usd["remarque"] = "Tirelire en dollars"
tirelires_usd[["numero_tirelire", "monnaie", "remarque"]]

## 22. Pourquoi Pandas est rapide

Pandas travaille sur TOUTE une colonne d'un coup (ça s'appelle "vectoriser"), au lieu
de regarder les tirelires une par une avec une boucle. C'est beaucoup plus rapide.

In [ ]:
import time

depart = time.perf_counter()
resultat_boucle = []
for valeur in tirelires["argent_dedans"]:                 # une boucle : on regarde chaque tirelire une par une
    resultat_boucle.append(valeur * 2 if pd.notna(valeur) else None)
duree_boucle = time.perf_counter() - depart

depart = time.perf_counter()
resultat_direct = tirelires["argent_dedans"] * 2           # vectorisé : toute la colonne d'un coup
duree_directe = time.perf_counter() - depart

print(f"Avec une boucle : {duree_boucle*1000:.3f} ms")
print(f"Vectorisé       : {duree_directe*1000:.3f} ms")

## 23. Tout refaire d'un coup avec une fonction

Une fois qu'on connaît toutes les étapes, on peut les ranger dans une seule fonction,
pour ne plus jamais avoir à les retaper.

In [ ]:
def ouvrir_et_nettoyer_les_tirelires():
    """Ouvre CTR.csv et le nettoie, en une seule fois."""
    df = pd.read_csv("../data/CTR.csv", sep=";", encoding="cp1252")   # 1. on ouvre le fichier
    df = df.replace(".", pd.NA)                                        # 2. les points deviennent des cases vides
    df["SLD_CTR"] = pd.to_numeric(df["SLD_CTR"], errors="coerce")      # 3. le solde devient un vrai nombre
    df["DAT_OUV_CTR"] = pd.to_datetime(df["DAT_OUV_CTR"], format="%Y-%m-%d", errors="coerce")   # 4. vraie date
    df["statut"] = df["COD_ECV_CTR"].map({4: "Ouverte", 6: "Fermée"})  # 5. un mot au lieu d'un code
    return df

tirelires_propres = ouvrir_et_nettoyer_les_tirelires()
tirelires_propres.info()

## 24. Fiche récap — toutes les fonctions vues dans ce notebook

| Fonction | À quoi ça sert (en très simple) |
|---|---|
| `pd.read_csv()` | Ouvrir un fichier et en faire un tableau |
| `.head()` / `.tail()` | Voir le début / la fin du tableau |
| `.sample()` | Voir des lignes prises au hasard |
| `.shape` | Savoir combien il y a de lignes et de colonnes |
| `.columns` | La liste des noms de colonnes |
| `.info()` / `.dtypes` | Le type de chaque colonne |
| `.describe()` | Des statistiques sur les colonnes de nombres |
| `.rename()` | Changer le nom d'une colonne |
| `df["col"]` / `df[["c1","c2"]]` | Choisir une ou plusieurs colonnes |
| `.select_dtypes()` | Choisir les colonnes d'un certain type |
| `.loc[]` / `.iloc[]` | Choisir une ligne précise |
| `df[condition]` | Garder seulement certaines lignes |
| `&`, `\|`, `~`, `.isin()` | Combiner ou tester des conditions |
| `.replace()` | Remplacer une valeur par une autre |
| `.isna()` / `.notna()` | Savoir si une case est vide |
| `.dropna()` / `.fillna()` | Enlever ou remplacer les cases vides |
| `pd.to_numeric()` / `pd.to_datetime()` | Transformer du texte en nombre / en date |
| `.map()` | Remplacer un code par un mot |
| `.sort_values()` | Trier le tableau |
| `.nlargest()` / `.nsmallest()` | Les plus grandes / petites valeurs |
| `np.where()` | Un "SI... SINON..." sur toute une colonne |
| `pd.cut()` | Ranger des nombres dans des tranches |
| `.apply()` | Appliquer sa propre fonction à une colonne |
| `.str....` | Manipuler du texte (majuscules, longueur...) |
| `.dt....` | Manipuler des dates (année, mois...) |
| `.duplicated()` / `.drop_duplicates()` | Trouver / enlever les doublons |
| `.unique()` / `.nunique()` / `.value_counts()` | Compter les valeurs différentes |
| `.groupby()` / `.agg()` / `.transform()` | Faire des paquets et calculer par paquet |
| `pd.crosstab()` / `.pivot_table()` | Tableaux qui croisent deux informations |
| `.merge()` | Assembler deux tableaux grâce à une colonne commune |
| `pd.concat()` | Empiler deux tableaux l'un sous l'autre |
| `.set_index()` / `.reset_index()` | Changer / remettre la numérotation des lignes |
| `.cumsum()` | Une addition qui grossit au fil des lignes |
| `.to_csv()` | Enregistrer un tableau dans un fichier |
| `.copy()` | Faire une vraie copie avant de modifier |

**Bravo, tu as vu TOUTES les fonctions Pandas principales, avec un seul petit tableau
de tirelires !**